name: Build and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build . --file Dockerfile --tag artty123/client-meowwoof:latest

      - name: Push docker image to Docker Hub
        run: docker push artty123/client-meowwoof:latest
  deploy-google-cloud:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Set up Google Cloud credentials
          uses: google-github-actions/setup-gcloud@v2
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
      - name: Deploy to Google Cloud Run
          run:
            gcloud run deploy client-meowwoof \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/client-meowwoof:latest \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated

    